# Params for tweets classifier

TRAIN_SIZE = 100
TRAIN_FEMALE_RATIO = 1.3
TRAIN_MALE_RATIO = 1

KEYWORD_SENSITIVITY = 2
LANGUAGE_DETECTION = False
SPELLING_CHECK = False

MAX_TWEETS_FOR_EACH_USER = 20